package ch.hszt.mdp.chatplus.gui;

/**
 * 
 * @author pascalbeyeler
 */
public class ConnectionDialog extends javax.swing.JDialog {

	/** Creates new form LoginForm */
	public ConnectionDialog(java.awt.Frame parent, boolean modal) {
		super(parent, modal);
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */

	private void initComponents() {
		java.awt.GridBagConstraints gridBagConstraints;

		serverIPLabel = new javax.swing.JLabel();
		serverIPField = new javax.swing.JTextField();
		serverPortLabel = new javax.swing.JLabel();
		serverPortField = new javax.swing.JTextField();
		usernameField = new javax.swing.JTextField();
		usernameLabel = new javax.swing.JLabel();
		connectButton = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setTitle("Login details");
		setAlwaysOnTop(true);

		serverIPLabel.setText("Server IP:");

		serverIPField.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				serverIPFieldActionPerformed(evt);
			}
		});

		serverPortLabel.setText("Server Port:");

		serverPortField.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				serverPortFieldActionPerformed(evt);
			}
		});

		usernameField.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				usernameFieldActionPerformed(evt);
			}
		});

		usernameLabel.setText("Username:");

		connectButton.setText("Connect");
		connectButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				connectButtonActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout
				.setHorizontalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addGroup(
																				layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								serverPortLabel)
																						.addComponent(
																								serverIPLabel)
																						.addComponent(
																								usernameLabel))
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addGroup(
																				layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								serverIPField,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								264,
																								Short.MAX_VALUE)
																						.addComponent(
																								serverPortField,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								264,
																								Short.MAX_VALUE)
																						.addComponent(
																								usernameField,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								264,
																								Short.MAX_VALUE)))
														.addComponent(
																connectButton,
																javax.swing.GroupLayout.Alignment.TRAILING))
										.addContainerGap()));
		layout
				.setVerticalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																serverIPLabel)
														.addComponent(
																serverIPField,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																serverPortLabel)
														.addComponent(
																serverPortField,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																usernameField,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																usernameLabel))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(connectButton)
										.addContainerGap(
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)));

		pack();
	}

	private void serverIPFieldActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_serverIPFieldActionPerformed
		// TODO add your handling code here:
	}

	private void serverPortFieldActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_serverPortFieldActionPerformed
		// TODO add your handling code here:
	}

	private void connectButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_connectButtonActionPerformed
		// TODO add your handling code here:
	}

	private void usernameFieldActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_usernameFieldActionPerformed
		// TODO add your handling code here:
	}

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				ConnectionDialog dialog = new ConnectionDialog(
						new javax.swing.JFrame(), true);
				dialog.addWindowListener(new java.awt.event.WindowAdapter() {
					public void windowClosing(java.awt.event.WindowEvent e) {
						System.exit(0);
					}
				});
				dialog.setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton connectButton;
	private javax.swing.JTextField serverIPField;
	private javax.swing.JLabel serverIPLabel;
	private javax.swing.JTextField serverPortField;
	private javax.swing.JLabel serverPortLabel;
	private javax.swing.JTextField usernameField;
	private javax.swing.JLabel usernameLabel;
	// End of variables declaration//GEN-END:variables

}